# Generated by Django 4.0.5 on 2022-10-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_house_image_house_house_name_img_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
